'use strict';
const ROOT=document.getElementById('aplikasi-root');
const PARAMETER_URL=new URLSearchParams(window.location.search);
const TOKEN_WALI_AWAL=(PARAMETER_URL.get('wali')||'').trim();
const MODE_AWAL=TOKEN_WALI_AWAL?'PORTAL_WALI':'APLIKASI';
const STATE={token:sessionStorage.getItem('amm_token')||'',pengguna:null,hakAkses:[],halaman:'dashboard',halamanSantri:1,modalSubmit:null,dataKehadiran:[],master:{kelas:[],santri:[],pengajar:[],wali:[],materi:[]},timer:{}};
const INFO_HALAMAN={dashboard:['Dashboard','Ringkasan kegiatan dan perkembangan'],kehadiran:['Kehadiran','Pencatatan kehadiran santri per kelas'],setoran:['Setoran Mengaji','Catat capaian dan nilai pembelajaran'],santri:['Data Santri','Kelola profil dan riwayat santri'],pengajar:['Data Pengajar','Kelola pengajar dan kelas yang diampu'],wali:['Wali Santri','Kelola wali dan akses portal'],kelas:['Data Kelas','Kelompok belajar dan anggota kelas'],jadwal:['Jadwal Mengaji','Atur jadwal kegiatan pembelajaran'],materi:['Materi Belajar','Susun materi dan urutan pembelajaran'],target:['Target Belajar','Pantau target individu santri'],catatan:['Catatan Santri','Perkembangan, disiplin, dan pendampingan'],laporan:['Laporan','Laporan santri, kelas, kehadiran, dan setoran'],pengumuman:['Pengumuman','Informasi lembaga dan kelas'],pengguna:['Pengguna','Akun, peran, dan status akses'],pengaturan:['Pengaturan','Konfigurasi lembaga dan aplikasi'],audit:['Audit Log','Riwayat perubahan data penting'],backup:['Backup','Cadangan data Spreadsheet dan Drive']};

document.addEventListener('DOMContentLoaded',inisialisasiAplikasi);
function inisialisasiAplikasi(){
  document.getElementById('versi-aplikasi').textContent=ROOT.dataset.versi||'2.0.0';
  pasangNavigasi();
  if(MODE_AWAL==='PORTAL_WALI'){bukaPortalWali();return;}
  if(STATE.token){validasiSesiAwal();}else tampilkanLogin();
}
function pasangNavigasi(){document.querySelectorAll('[data-halaman]').forEach(btn=>btn.addEventListener('click',()=>{const h=btn.dataset.halaman;if(h==='lainnya'){document.getElementById('drawer-lainnya').classList.add('aktif');return;}navigasiKe(h);}));}
async function panggilServer(nama,...argumen){
  const controller=new AbortController();
  const timer=setTimeout(()=>controller.abort(),30000);
  try{
    const respons=await fetch('/api',{
      method:'POST',
      headers:{'Content-Type':'application/json','Accept':'application/json','X-Requested-With':'fetch'},
      body:JSON.stringify({aksi:nama,argumen}),
      credentials:'same-origin',
      signal:controller.signal
    });
    const teks=await respons.text();
    let hasil;
    try{hasil=JSON.parse(teks);}catch(parseError){
      throw new Error('Respons server tidak valid. Periksa deployment Netlify Function dan Google Apps Script.');
    }
    if(!respons.ok){
      throw new Error(hasil.pesan||`Permintaan gagal (${respons.status}).`);
    }
    return hasil;
  }catch(error){
    if(error&&error.name==='AbortError')throw new Error('Server membutuhkan waktu terlalu lama. Silakan coba kembali.');
    if(!navigator.onLine)throw new Error('Perangkat sedang offline. Sambungkan internet lalu coba kembali.');
    throw error;
  }finally{clearTimeout(timer);}
}
function tampilkanLoading(teks){const layar=document.getElementById('layar-memuat');layar.querySelector('strong').textContent=teks||'Memproses…';layar.classList.add('aktif');}
function sembunyikanLoading(){document.getElementById('layar-memuat').classList.remove('aktif');}
function tampilkanToast(pesan,jenis='sukses'){const el=document.createElement('div');el.className='toast '+(jenis==='gagal'?'gagal':'sukses');el.innerHTML=`<span>${jenis==='gagal'?'⚠':'✓'}</span><div><strong>${jenis==='gagal'?'Tidak berhasil':'Berhasil'}</strong><div>${escapeHtml(pesan||'')}</div></div>`;document.getElementById('toast-container').appendChild(el);setTimeout(()=>el.remove(),4500);}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function formatTanggal(v){if(!v)return'-';const s=String(v).substring(0,10).split('-');return s.length===3?`${s[2]}/${s[1]}/${s[0]}`:String(v);}
function formatTanggalWaktu(v){if(!v)return'-';return `${formatTanggal(String(v).substring(0,10))} ${String(v).substring(11,16)}`;}
function hariIni(){const d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),h=String(d.getDate()).padStart(2,'0');return `${d.getFullYear()}-${m}-${h}`;}
function awalBulan(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;}
function badge(status){const s=String(status||'-');let c='';if(/AKTIF|HADIR|LANJUT|LULUS|TERCAPAI|BERHASIL|BAIK/.test(s))c='sukses';else if(/ALPA|TERHAPUS|NONAKTIF|GAGAL|PENDAMPINGAN|DITOLAK/.test(s))c='bahaya';else if(/IZIN|SAKIT|TERLAMBAT|ULANG|TERTUNDA|DIAJUKAN/.test(s))c='peringatan';else c='info';return `<span class="badge ${c}">${escapeHtml(s.replaceAll('_',' '))}</span>`;}
function tabel(kolom,data,aksi){if(!data||!data.length)return '<div class="empty-state">Belum ada data yang dapat ditampilkan.</div>';return `<table class="data-table"><thead><tr>${kolom.map(c=>`<th>${escapeHtml(c.label)}</th>`).join('')}${aksi?'<th>Aksi</th>':''}</tr></thead><tbody>${data.map(row=>`<tr>${kolom.map(c=>`<td>${c.render?c.render(row):escapeHtml(row[c.key]??'-')}</td>`).join('')}${aksi?`<td>${aksi(row)}</td>`:''}</tr>`).join('')}</tbody></table>`;}
function opsiSelect(items,valueKey,labelKey,placeholder='Pilih data'){return `<option value="">${escapeHtml(placeholder)}</option>`+(items||[]).map(x=>`<option value="${escapeHtml(x[valueKey])}">${escapeHtml(typeof labelKey==='function'?labelKey(x):x[labelKey])}</option>`).join('');}
function nilaiForm(form){return Object.fromEntries(new FormData(form).entries());}
function debounce(kunci,fn){clearTimeout(STATE.timer[kunci]);STATE.timer[kunci]=setTimeout(fn,350);}

async function validasiSesiAwal(){tampilkanLoading('Memeriksa sesi…');try{const r=await panggilServer('validasiToken',STATE.token);if(!r.sukses)throw new Error(r.pesan);STATE.pengguna=r.data.pengguna;STATE.hakAkses=r.data.hak_akses||[];tampilkanAplikasi();await navigasiKe('dashboard');}catch(e){sessionStorage.removeItem('amm_token');STATE.token='';tampilkanLogin();}finally{sembunyikanLoading();}}
function tampilkanLogin(){document.getElementById('halaman-login').classList.remove('tersembunyi');document.getElementById('shell-aplikasi').classList.add('tersembunyi');document.getElementById('halaman-portal-wali').classList.add('tersembunyi');sembunyikanLoading();}
function tampilkanAplikasi(){document.getElementById('halaman-login').classList.add('tersembunyi');document.getElementById('shell-aplikasi').classList.remove('tersembunyi');const p=STATE.pengguna;document.getElementById('nama-pengguna').textContent=p.nama_lengkap;document.getElementById('peran-pengguna').textContent=p.peran.replaceAll('_',' ');document.getElementById('avatar-pengguna').textContent=(p.nama_lengkap||'A').charAt(0).toUpperCase();aturTampilanPeran();muatKonfigurasiPublik();}
async function muatKonfigurasiPublik(){try{const r=await panggilServer('ambilKonfigurasiPublik');if(r.sukses){document.getElementById('brand-lembaga').textContent=r.data.nama_lembaga||'Lembaga Al-Qur\'an';document.getElementById('brand-nama').textContent=r.data.nama_aplikasi||'Monitoring Mengaji';document.documentElement.style.setProperty('--utama',r.data.warna_utama||'#087f5b');}}catch(e){}}
function aturTampilanPeran(){const role=STATE.pengguna.peran;document.querySelectorAll('.khusus-admin').forEach(x=>x.classList.toggle('tersembunyi',role!=='SUPER_ADMIN'));document.querySelectorAll('.khusus-pengelola').forEach(x=>x.classList.toggle('tersembunyi',!['SUPER_ADMIN','PENGELOLA'].includes(role)));document.querySelectorAll('.khusus-admin-pengelola').forEach(x=>x.classList.toggle('tersembunyi',!['SUPER_ADMIN','PENGELOLA','ADMIN'].includes(role)));const menu={PENGAJAR:['dashboard','kehadiran','setoran','santri','kelas','jadwal','materi','target','catatan','laporan','pengumuman','pengaturan'],ADMIN:['dashboard','kehadiran','setoran','santri','pengajar','wali','kelas','jadwal','materi','target','catatan','laporan','pengumuman','pengaturan'],PENGELOLA:null,SUPER_ADMIN:null};if(menu[role])document.querySelectorAll('.nav-sidebar [data-halaman]').forEach(x=>x.classList.toggle('tersembunyi',!menu[role].includes(x.dataset.halaman)));}
async function prosesLogin(e){e.preventDefault();const f=nilaiForm(e.target);tampilkanLoading('Memverifikasi akun…');try{const r=await panggilServer('autentikasiMasuk',f.nama_pengguna,f.password,navigator.userAgent);if(!r.sukses)throw new Error(r.pesan);STATE.token=r.data.token;STATE.pengguna=r.data.pengguna;STATE.hakAkses=r.data.hak_akses||[];sessionStorage.setItem('amm_token',STATE.token);tampilkanToast(r.pesan);tampilkanAplikasi();if(r.data.wajib_ganti_password)setTimeout(formGantiPassword,500);await navigasiKe('dashboard');}catch(err){tampilkanToast(err.message,'gagal');}finally{sembunyikanLoading();}}
function togglePassword(){const i=document.getElementById('input-password');i.type=i.type==='password'?'text':'password';}
async function keluarAplikasi(){if(!confirm('Keluar dari aplikasi sekarang?'))return;tampilkanLoading('Mengakhiri sesi…');try{if(STATE.token)await panggilServer('autentikasiKeluar',STATE.token);}catch(e){}sessionStorage.removeItem('amm_token');STATE.token='';STATE.pengguna=null;tampilkanLogin();sembunyikanLoading();}
function toggleSidebar(){document.getElementById('sidebar').classList.toggle('ciut');}
function toggleSidebarMobile(){document.getElementById('sidebar').classList.toggle('mobile-buka');}
function tutupDrawer(){document.getElementById('drawer-lainnya').classList.remove('aktif');}
async function navigasiKe(h){tutupDrawer();STATE.halaman=h;document.getElementById('sidebar').classList.remove('mobile-buka');document.querySelectorAll('[data-halaman]').forEach(x=>x.classList.toggle('aktif',x.dataset.halaman===h));const info=INFO_HALAMAN[h]||[h,''];document.getElementById('judul-halaman').textContent=info[0];document.getElementById('subjudul-halaman').textContent=info[1];const tpl=document.getElementById('tpl-'+h);if(!tpl)return;const konten=document.getElementById('konten-halaman');konten.innerHTML='';konten.appendChild(tpl.content.cloneNode(true));aturTampilanPeran();await muatHalamanAktif();}
async function muatHalamanAktif(){const map={dashboard:muatDashboard,santri:muatSantri,pengajar:muatPengajar,wali:muatWali,kelas:muatKelas,jadwal:muatJadwal,kehadiran:initKehadiran,materi:muatMateri,setoran:initSetoran,target:muatTarget,catatan:muatCatatan,laporan:initLaporan,pengumuman:muatPengumuman,pengguna:muatPengguna,pengaturan:muatPengaturan,audit:muatAudit,backup:muatBackup};if(map[STATE.halaman]){tampilkanLoading('Memuat data…');try{await map[STATE.halaman]();}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}}

async function muatDashboard(){const r=await panggilServer('ambilDashboard',STATE.token,{});if(!r.sukses)throw new Error(r.pesan);const d=r.data;document.getElementById('dashboard-salam').innerHTML=`<h2>Assalamu'alaikum, ${escapeHtml(d.pengguna.nama_lengkap)}</h2><p>${new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} · Semoga kegiatan mengaji hari ini berjalan lancar.</p>`;const stat=[['Santri Aktif',d.ringkasan.santri_aktif,'♙'],['Kelas Aktif',d.ringkasan.kelas_aktif,'▦'],['Kehadiran Hari Ini',d.ringkasan.kehadiran_hari_ini,'✓'],['Setoran Hari Ini',d.ringkasan.setoran_hari_ini,'▤']];document.getElementById('dashboard-statistik').innerHTML=stat.map(s=>`<div class="stat-card"><div><small>${s[0]}</small><strong>${s[1]}</strong></div><div class="stat-icon">${s[2]}</div></div>`).join('');renderGrafik('grafik-kehadiran',d.grafik_kehadiran,x=>x.total?Math.round(x.hadir*100/x.total):0,x=>`${x.hadir}/${x.total}`);renderGrafik('grafik-nilai',d.grafik_perkembangan,x=>x.nilai,x=>x.nilai);document.getElementById('jadwal-hari-ini').innerHTML=d.jadwal_hari_ini.length?d.jadwal_hari_ini.map(x=>`<div class="list-item"><div><strong>${escapeHtml(x.jenis_kegiatan)}</strong><small>${escapeHtml(x.hari)} · ${escapeHtml(x.jam_mulai)}–${escapeHtml(x.jam_selesai)}</small></div>${badge(x.status_jadwal)}</div>`).join(''):'<div class="empty-state">Tidak ada jadwal hari ini.</div>';document.getElementById('santri-perhatian').innerHTML=d.santri_perlu_perhatian.length?d.santri_perlu_perhatian.map(x=>`<div class="list-item"><div><strong>${escapeHtml(x.nama_lengkap)}</strong><small>Nilai ${escapeHtml(x.nilai_akhir)} · ${formatTanggal(x.tanggal)}</small></div>${badge('PENDAMPINGAN')}</div>`).join(''):'<div class="empty-state">Tidak ada santri yang perlu perhatian khusus.</div>';document.getElementById('aktivitas-terbaru').innerHTML=tabel([{label:'Waktu',render:x=>formatTanggalWaktu(x.waktu)},{label:'Pengguna',key:'nama_pengguna'},{label:'Modul',key:'modul'},{label:'Aksi',render:x=>badge(x.aksi)},{label:'Status',render:x=>badge(x.status)}],d.aktivitas_terbaru);}
function renderGrafik(id,data,nilaiFn,labelFn){const max=Math.max(100,...data.map(nilaiFn));document.getElementById(id).innerHTML=data.map(x=>{const v=nilaiFn(x);return `<div class="bar-wrap"><span class="bar-value">${escapeHtml(labelFn(x))}</span><div class="bar" style="height:${Math.max(3,v/max*145)}px"></div><span class="bar-label">${String(x.tanggal).substring(5)}</span></div>`;}).join('');}

function debounceMuatSantri(){debounce('santri',()=>muatSantri());}
async function muatSantri(){const cari=document.getElementById('cari-santri')?.value||'',status=document.getElementById('filter-status-santri')?.value||'';const r=await panggilServer('daftarSantri',STATE.token,{cari,status},STATE.halamanSantri,20);if(!r.sukses)throw new Error(r.pesan);document.getElementById('tabel-santri').innerHTML=tabel([{label:'Nomor Induk',key:'nomor_induk'},{label:'Nama Santri',render:x=>`<strong>${escapeHtml(x.nama_lengkap)}</strong><br><small>${escapeHtml(x.nama_panggilan||'')}</small>`},{label:'Program',key:'jenis_program'},{label:'Tingkat',key:'tingkat_aktif'},{label:'WhatsApp Wali',key:'nomor_whatsapp_wali'},{label:'Status',render:x=>badge(x.status_santri)}],r.data.item,x=>`<button class="btn kecil sekunder" onclick="lihatSantri('${x.id_santri}')">Detail</button>`);const p=document.getElementById('paginasi-santri');p.innerHTML=`<button class="btn kecil sekunder" ${r.data.halaman<=1?'disabled':''} onclick="gantiHalamanSantri(${r.data.halaman-1})">Sebelumnya</button><span class="badge">${r.data.halaman}/${r.data.total_halaman}</span><button class="btn kecil sekunder" ${r.data.halaman>=r.data.total_halaman?'disabled':''} onclick="gantiHalamanSantri(${r.data.halaman+1})">Berikutnya</button>`;}
function gantiHalamanSantri(n){STATE.halamanSantri=n;muatSantri();}
async function lihatSantri(id){tampilkanLoading('Memuat detail santri…');try{const r=await panggilServer('detailSantri',STATE.token,id);if(!r.sukses)throw new Error(r.pesan);const s=r.data;const html=`<div class="span-2"><div class="hero-ringkas"><h2>${escapeHtml(s.nama_lengkap)}</h2><p>${escapeHtml(s.nomor_induk)} · ${escapeHtml(s.jenis_program)} · ${escapeHtml(s.tingkat_aktif||'-')}</p></div></div><div><strong>Status</strong><p>${badge(s.status_santri)}</p></div><div><strong>Tanggal Masuk</strong><p>${formatTanggal(s.tanggal_masuk)}</p></div><div class="span-2"><strong>Alamat</strong><p>${escapeHtml(s.alamat||'-')}</p></div><div class="span-2"><strong>Ringkasan Riwayat</strong><p>${s.riwayat.kehadiran.length} kehadiran · ${s.riwayat.setoran.length} setoran · ${s.riwayat.target.length} target · ${s.riwayat.catatan.length} catatan</p></div>`;bukaModalKonten('Detail Santri','Profil dan riwayat ringkas',html);}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}
async function formTambahSantri(){await pastikanWali();bukaForm('Tambah Santri','Isi data utama santri',[f('nomor_induk','Nomor Induk','text',true),f('nama_lengkap','Nama Lengkap','text',true),f('nama_panggilan','Nama Panggilan'),selectF('jenis_kelamin','Jenis Kelamin',['L','P']),f('tempat_lahir','Tempat Lahir'),f('tanggal_lahir','Tanggal Lahir','date'),f('alamat','Alamat','textarea',false,'span-2'),selectObjF('id_wali_utama','Wali Utama',STATE.master.wali,'id_wali',x=>`${x.nama_lengkap} · ${x.nomor_whatsapp}`,true),f('tanggal_masuk','Tanggal Masuk','date',true,hariIni()),selectF('jenis_program','Program',['IQRA','AL_QURAN','HAFALAN','TAJWID','DOA_HARIAN'],true),f('tingkat_aktif','Tingkat Awal')],async data=>panggilServer('simpanSantri',STATE.token,data),muatSantri);}

function debounceMuatPengajar(){debounce('pengajar',muatPengajar)}
async function muatPengajar(){const r=await panggilServer('daftarPengajar',STATE.token,{cari:document.getElementById('cari-pengajar')?.value||''},1,100);if(!r.sukses)throw new Error(r.pesan);document.getElementById('tabel-pengajar').innerHTML=tabel([{label:'Nomor',key:'nomor_pengajar'},{label:'Nama',key:'nama_lengkap'},{label:'WhatsApp',key:'nomor_whatsapp'},{label:'Keahlian',key:'keahlian'},{label:'Status',render:x=>badge(x.status_pengajar)}],r.data.item);}
function formTambahPengajar(){bukaForm('Tambah Pengajar','Data identitas dan kontak',[f('nomor_pengajar','Nomor Pengajar','text',true),f('nama_lengkap','Nama Lengkap','text',true),selectF('jenis_kelamin','Jenis Kelamin',['L','P']),f('nomor_whatsapp','Nomor WhatsApp','tel'),f('email','Email','email'),f('tanggal_bergabung','Tanggal Bergabung','date',false,hariIni()),f('keahlian','Keahlian'),f('alamat','Alamat','textarea',false,'span-2')],async d=>panggilServer('simpanPengajar',STATE.token,d),muatPengajar);}

function debounceMuatWali(){debounce('wali',muatWali)}
async function muatWali(){const r=await panggilServer('daftarWali',STATE.token,{cari:document.getElementById('cari-wali')?.value||''},1,100);if(!r.sukses)throw new Error(r.pesan);document.getElementById('tabel-wali').innerHTML=tabel([{label:'Nama Wali',key:'nama_lengkap'},{label:'Hubungan',key:'hubungan'},{label:'WhatsApp',key:'nomor_whatsapp'},{label:'Pekerjaan',key:'pekerjaan'},{label:'Status',render:x=>badge(x.status_wali)}],r.data.item,x=>`<button class="btn kecil sekunder" onclick="buatTautanWali('${x.id_wali}')">Buat Tautan</button>`);}
function formTambahWali(){bukaForm('Tambah Wali Santri','Data wali dan kontak',[f('nama_lengkap','Nama Lengkap','text',true),selectF('hubungan','Hubungan',['AYAH','IBU','WALI','SAUDARA'],true),f('nomor_whatsapp','Nomor WhatsApp','tel',true),f('email','Email','email'),f('pekerjaan','Pekerjaan'),f('alamat','Alamat','textarea',false,'span-2')],async d=>panggilServer('simpanWali',STATE.token,d),muatWali);}
async function buatTautanWali(id){tampilkanLoading('Membuat tautan portal…');try{const r=await panggilServer('buatTokenPortalWali',STATE.token,id,30);if(!r.sukses)throw new Error(r.pesan);await navigator.clipboard.writeText(r.data.url).catch(()=>{});tampilkanToast('Tautan portal dibuat dan disalin.');bukaModalKonten('Tautan Portal Wali','Berlaku sampai '+formatTanggalWaktu(r.data.kedaluwarsa_pada),`<div class="span-2"><label>Tautan Akses<input value="${escapeHtml(r.data.url)}" readonly onclick="this.select()"></label><p>Bagikan tautan ini hanya kepada wali yang berhak.</p></div>`);}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}

function debounceMuatKelas(){debounce('kelas',muatKelas)}
async function muatKelas(){const r=await panggilServer('daftarKelas',STATE.token,{cari:document.getElementById('cari-kelas')?.value||''},1,100);if(!r.sukses)throw new Error(r.pesan);document.getElementById('grid-kelas').innerHTML=r.data.item.length?r.data.item.map(x=>`<div class="item-card"><div class="card-header"><div><h3>${escapeHtml(x.nama_kelas)}</h3><p>${escapeHtml(x.kode_kelas)} · ${escapeHtml(x.tingkat||'-')}</p></div>${badge(x.status_kelas)}</div><div class="meta"><span class="badge info">${x.jumlah_anggota} Santri</span><span class="badge">Kapasitas ${x.kapasitas}</span><span class="badge">${escapeHtml(x.lokasi||'-')}</span></div><div class="actions"><button class="btn kecil sekunder" onclick="lihatKelas('${x.id_kelas}')">Detail</button><button class="btn kecil utama khusus-admin-pengelola" onclick="formTambahAnggota('${x.id_kelas}')">Tambah Anggota</button></div></div>`).join(''):'<div class="empty-state">Belum ada kelas.</div>';aturTampilanPeran();}
async function formTambahKelas(){await pastikanPengajar();bukaForm('Tambah Kelas','Identitas dan pengajar kelas',[f('kode_kelas','Kode Kelas','text',true),f('nama_kelas','Nama Kelas','text',true),f('tingkat','Tingkat'),selectObjF('id_pengajar_utama','Pengajar Utama',STATE.master.pengajar,'id_pengajar','nama_lengkap',true),selectObjF('id_pengajar_pendamping','Pengajar Pendamping',STATE.master.pengajar,'id_pengajar','nama_lengkap'),f('kapasitas','Kapasitas','number',true,20),f('lokasi','Lokasi'),f('tahun_ajaran','Tahun Ajaran','text',false,'2026/2027'),f('periode','Periode','text',false,'Semester Ganjil')],async d=>panggilServer('simpanKelas',STATE.token,d),muatKelas);}
async function lihatKelas(id){tampilkanLoading('Memuat kelas…');try{const r=await panggilServer('detailKelas',STATE.token,id);if(!r.sukses)throw new Error(r.pesan);const k=r.data;const html=`<div class="span-2"><h3>${escapeHtml(k.nama_kelas)}</h3><p>${escapeHtml(k.kode_kelas)} · ${escapeHtml(k.lokasi||'-')}</p></div><div class="span-2">${tabel([{label:'Nomor Induk',render:x=>escapeHtml(x.santri?.nomor_induk||'-')},{label:'Nama Santri',render:x=>escapeHtml(x.santri?.nama_lengkap||'-')},{label:'Mulai',render:x=>formatTanggal(x.tanggal_mulai)}],k.anggota)}</div>`;bukaModalKonten('Detail Kelas',`${k.anggota.length} anggota aktif`,html);}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}
async function formTambahAnggota(idKelas){await pastikanSantri();bukaForm('Tambah Anggota Kelas','Pilih santri yang akan ditempatkan',[selectObjF('id_santri','Santri',STATE.master.santri,'id_santri',x=>`${x.nomor_induk} · ${x.nama_lengkap}`,true),f('tanggal_mulai','Tanggal Mulai','date',true,hariIni())],async d=>panggilServer('tambahAnggotaKelas',STATE.token,idKelas,d.id_santri,d.tanggal_mulai),muatKelas);}

async function muatJadwal(){const r=await panggilServer('daftarJadwal',STATE.token,{hari:document.getElementById('filter-hari-jadwal')?.value||''},1,100);if(!r.sukses)throw new Error(r.pesan);document.getElementById('tabel-jadwal').innerHTML=tabel([{label:'Hari',key:'hari'},{label:'Waktu',render:x=>`${escapeHtml(x.jam_mulai)}–${escapeHtml(x.jam_selesai)}`},{label:'Kelas',render:x=>escapeHtml(x.kelas?.nama_kelas||'-')},{label:'Pengajar',render:x=>escapeHtml(x.pengajar?.nama_lengkap||'-')},{label:'Lokasi',key:'lokasi'},{label:'Status',render:x=>badge(x.status_jadwal)}],r.data.item);}
async function formTambahJadwal(){await Promise.all([pastikanKelas(),pastikanPengajar()]);bukaForm('Tambah Jadwal','Atur hari dan waktu kegiatan',[selectObjF('id_kelas','Kelas',STATE.master.kelas,'id_kelas','nama_kelas',true),selectF('hari','Hari',['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'],true),f('jam_mulai','Jam Mulai','time',true),f('jam_selesai','Jam Selesai','time',true),selectObjF('id_pengajar','Pengajar',STATE.master.pengajar,'id_pengajar','nama_lengkap',true),f('lokasi','Lokasi'),f('jenis_kegiatan','Jenis Kegiatan','text',false,'Mengaji Reguler')],async d=>panggilServer('simpanJadwal',STATE.token,d),muatJadwal);}

async function initKehadiran(){await pastikanKelas();const sel=document.getElementById('kehadiran-kelas');sel.innerHTML=opsiSelect(STATE.master.kelas,'id_kelas','nama_kelas','Pilih kelas');document.getElementById('kehadiran-tanggal').value=hariIni();if(STATE.master.kelas.length){sel.value=STATE.master.kelas[0].id_kelas;await muatFormKehadiran();}}
async function muatFormKehadiran(){const kelas=document.getElementById('kehadiran-kelas')?.value,tanggal=document.getElementById('kehadiran-tanggal')?.value;if(!kelas||!tanggal)return;const r=await panggilServer('ambilFormKehadiran',STATE.token,kelas,tanggal);if(!r.sukses)throw new Error(r.pesan);STATE.dataKehadiran=r.data.santri.map(x=>({...x,status_kehadiran:x.status_kehadiran==='BELUM_DIISI'?'HADIR':x.status_kehadiran}));renderKehadiran();}
function renderKehadiran(){const wrap=document.getElementById('daftar-kehadiran');if(!STATE.dataKehadiran.length){wrap.innerHTML='<div class="empty-state">Tidak ada anggota aktif pada kelas ini.</div>';return;}wrap.innerHTML=STATE.dataKehadiran.map((x,i)=>`<div class="attendance-row"><div class="attendance-person"><strong>${escapeHtml(x.nama_lengkap)}</strong><small>${escapeHtml(x.nomor_induk)}</small></div>${['HADIR','IZIN','SAKIT','ALPA','TERLAMBAT'].map(s=>`<button type="button" class="status-btn ${x.status_kehadiran===s?'aktif':''}" onclick="ubahStatusKehadiran(${i},'${s}')">${s}</button>`).join('')}<input placeholder="Catatan" value="${escapeHtml(x.catatan||'')}" oninput="STATE.dataKehadiran[${i}].catatan=this.value"></div>`).join('');const count={HADIR:0,IZIN:0,SAKIT:0,ALPA:0,TERLAMBAT:0};STATE.dataKehadiran.forEach(x=>count[x.status_kehadiran]++);document.getElementById('ringkasan-status-kehadiran').textContent=Object.entries(count).map(x=>`${x[0]} ${x[1]}`).join(' · ');}
function ubahStatusKehadiran(i,s){STATE.dataKehadiran[i].status_kehadiran=s;renderKehadiran();}
function tandaiSemuaHadir(){STATE.dataKehadiran.forEach(x=>x.status_kehadiran='HADIR');renderKehadiran();}
async function simpanKehadiran(){const existing=STATE.dataKehadiran.filter(x=>x.id_kehadiran);if(existing.length){tampilkanToast('Data tanggal ini sudah tersimpan. Koreksi dilakukan melalui data kehadiran tersimpan.','gagal');return;}if(!STATE.dataKehadiran.length)return;tampilkanLoading('Menyimpan kehadiran…');try{const r=await panggilServer('simpanKehadiranBatch',STATE.token,{id_kelas:document.getElementById('kehadiran-kelas').value,tanggal:document.getElementById('kehadiran-tanggal').value,item:STATE.dataKehadiran.map(x=>({id_santri:x.id_santri,status_kehadiran:x.status_kehadiran,catatan:x.catatan||''}))});if(!r.sukses)throw new Error(r.pesan);tampilkanToast(r.pesan);await muatFormKehadiran();}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}

function debounceMuatMateri(){debounce('materi',muatMateri)}
async function muatMateri(){const r=await panggilServer('daftarMateri',STATE.token,{cari:document.getElementById('cari-materi')?.value||''},1,200);if(!r.sukses)throw new Error(r.pesan);document.getElementById('tabel-materi').innerHTML=tabel([{label:'Urutan',key:'urutan'},{label:'Kode',key:'kode_materi'},{label:'Nama Materi',key:'nama_materi'},{label:'Jenis',key:'jenis_materi'},{label:'Tingkat',key:'tingkat'},{label:'Status',render:x=>badge(x.status_materi)}],r.data.item);}
function formTambahMateri(){bukaForm('Tambah Materi','Susun materi belajar',[f('kode_materi','Kode Materi','text',true),f('nama_materi','Nama Materi','text',true),selectF('jenis_materi','Jenis',['IQRA','AL_QURAN','HAFALAN','TAJWID','DOA_HARIAN','FIKIH_DASAR','ADAB','PRAKTIK'],true),f('tingkat','Tingkat'),f('urutan','Urutan','number',true),f('deskripsi','Deskripsi','textarea',false,'span-2')],async d=>panggilServer('simpanMateri',STATE.token,d),muatMateri);}

async function initSetoran(){await Promise.all([pastikanKelas(),pastikanMateri()]);document.getElementById('setoran-kelas').innerHTML=opsiSelect(STATE.master.kelas,'id_kelas','nama_kelas','Pilih kelas');document.getElementById('setoran-materi').innerHTML=opsiSelect(STATE.master.materi,'id_materi','nama_materi','Pilih materi');document.querySelector('#form-setoran [name=tanggal]').value=hariIni();if(STATE.master.kelas.length){document.getElementById('setoran-kelas').value=STATE.master.kelas[0].id_kelas;await muatSantriSetoran();}}
async function muatSantriSetoran(){const id=document.getElementById('setoran-kelas').value;if(!id)return;const r=await panggilServer('daftarAnggotaKelas',STATE.token,id);if(!r.sukses)throw new Error(r.pesan);const data=r.data.map(x=>x.santri).filter(Boolean);document.getElementById('setoran-santri').innerHTML=opsiSelect(data,'id_santri',x=>`${x.nomor_induk} · ${x.nama_lengkap}`,'Pilih santri');if(data.length){document.getElementById('setoran-santri').value=data[0].id_santri;await muatRingkasanSetoran();}}
async function muatRingkasanSetoran(){const id=document.getElementById('setoran-santri').value;if(!id)return;const r=await panggilServer('ambilFormSetoran',STATE.token,id);if(!r.sukses)throw new Error(r.pesan);const d=r.data,ter=d.setoran_terakhir;document.getElementById('ringkasan-setoran').innerHTML=`<div class="list-item"><div><strong>${escapeHtml(d.santri.nama_lengkap)}</strong><small>${escapeHtml(d.santri.nomor_induk)} · ${escapeHtml(d.santri.tingkat_aktif||'-')}</small></div>${badge(d.santri.status_santri)}</div>${ter?`<div class="list-item"><div><strong>Setoran Terakhir</strong><small>${formatTanggal(ter.tanggal)} · Nilai ${ter.nilai_akhir}</small></div>${badge(ter.rekomendasi)}</div>`:'<div class="empty-state">Belum ada setoran sebelumnya.</div>'}${d.target_aktif.map(t=>`<div class="list-item"><div><strong>${escapeHtml(t.nama_target)}</strong><small>${t.persentase}% tercapai</small></div>${badge(t.status_target)}</div>`).join('')}`;}
async function prosesSimpanSetoran(e){e.preventDefault();const d=nilaiForm(e.target);d.id_kelas=document.getElementById('setoran-kelas').value;d.id_santri=document.getElementById('setoran-santri').value;if(!d.id_kelas||!d.id_santri){tampilkanToast('Pilih kelas dan santri.','gagal');return;}tampilkanLoading('Menyimpan setoran…');try{const r=await panggilServer('simpanSetoran',STATE.token,d);if(!r.sukses)throw new Error(r.pesan);tampilkanToast(`${r.pesan} Nilai akhir ${r.data.nilai_akhir}, rekomendasi ${r.data.rekomendasi}.`);await muatRingkasanSetoran();e.target.reset();e.target.querySelector('[name=tanggal]').value=hariIni();['nilai_kelancaran','nilai_makhraj','nilai_tajwid'].forEach(n=>e.target.querySelector(`[name=${n}]`).value=80);e.target.querySelector('[name=nilai_adab]').value=85;e.target.querySelector('[name=nilai_hafalan]').value=0;}catch(err){tampilkanToast(err.message,'gagal');}finally{sembunyikanLoading();}}
async function muatRiwayatSetoran(){const id=document.getElementById('setoran-santri').value;if(!id)return;const r=await panggilServer('riwayatSetoranSantri',STATE.token,id);if(!r.sukses)throw new Error(r.pesan);document.getElementById('riwayat-setoran').innerHTML=r.data.item.slice(0,10).map(x=>`<div class="list-item"><div><strong>${formatTanggal(x.tanggal)} · ${escapeHtml(x.jenis_setoran)}</strong><small>Nilai ${x.nilai_akhir} · ${escapeHtml(x.catatan||'')}</small></div>${badge(x.rekomendasi)}</div>`).join('')||'<div class="empty-state">Belum ada riwayat.</div>';}

async function muatTarget(){const r=await panggilServer('daftarTarget',STATE.token,{status:document.getElementById('filter-target-status')?.value||''},1,200);if(!r.sukses)throw new Error(r.pesan);const sm={};(await ambilSantriMasterAman()).forEach(s=>sm[s.id_santri]=s);document.getElementById('tabel-target').innerHTML=tabel([{label:'Santri',render:x=>escapeHtml(sm[x.id_santri]?.nama_lengkap||x.id_santri)},{label:'Target',key:'nama_target'},{label:'Progres',render:x=>`<strong>${x.persentase}%</strong><br><small>${x.nilai_terkini}/${x.nilai_target} ${escapeHtml(x.satuan||'')}</small>`},{label:'Tanggal Target',render:x=>formatTanggal(x.tanggal_target)},{label:'Status',render:x=>badge(x.status_target)}],r.data.item);}
async function formTambahTarget(){await Promise.all([pastikanSantri(),pastikanKelas(),pastikanMateri()]);bukaForm('Buat Target Santri','Tentukan indikator dan batas waktu',[selectObjF('id_santri','Santri',STATE.master.santri,'id_santri',x=>`${x.nomor_induk} · ${x.nama_lengkap}`,true),selectObjF('id_kelas','Kelas',STATE.master.kelas,'id_kelas','nama_kelas'),selectObjF('id_materi','Materi',STATE.master.materi,'id_materi','nama_materi'),f('nama_target','Nama Target','text',true),f('indikator_target','Indikator'),f('nilai_awal','Nilai Awal','number',false,0),f('nilai_target','Nilai Target','number',true),f('nilai_terkini','Nilai Terkini','number',false,0),f('satuan','Satuan','text',false,'halaman'),f('tanggal_mulai','Tanggal Mulai','date',true,hariIni()),f('tanggal_target','Tanggal Target','date',true),f('catatan','Catatan','textarea',false,'span-2')],async d=>panggilServer('buatTarget',STATE.token,d),muatTarget);}

async function muatCatatan(){const r=await panggilServer('daftarCatatan',STATE.token,{kategori:document.getElementById('filter-catatan-kategori')?.value||''},1,200);if(!r.sukses)throw new Error(r.pesan);const sm={};(await ambilSantriMasterAman()).forEach(s=>sm[s.id_santri]=s);document.getElementById('grid-catatan').innerHTML=r.data.item.length?r.data.item.map(x=>`<div class="item-card"><div class="card-header"><div><h3>${escapeHtml(x.judul)}</h3><p>${formatTanggal(x.tanggal)} · ${escapeHtml(sm[x.id_santri]?.nama_lengkap||'Santri')}</p></div>${badge(x.kategori)}</div><p>${escapeHtml(x.isi_catatan)}</p><div class="meta">${badge(x.visibilitas)} ${badge(x.status_tindak_lanjut)}</div></div>`).join(''):'<div class="empty-state">Belum ada catatan.</div>';}
async function formTambahCatatan(){await Promise.all([pastikanSantri(),pastikanKelas()]);bukaForm('Tambah Catatan Santri','Catatan perkembangan dan tindak lanjut',[selectObjF('id_santri','Santri',STATE.master.santri,'id_santri',x=>`${x.nomor_induk} · ${x.nama_lengkap}`,true),selectObjF('id_kelas','Kelas',STATE.master.kelas,'id_kelas','nama_kelas'),f('tanggal','Tanggal','date',true,hariIni()),selectF('kategori','Kategori',['PERKEMBANGAN','KEDISIPLINAN','PENDAMPINGAN','PRESTASI','KOMUNIKASI_WALI'],true),f('judul','Judul','text',true),selectF('visibilitas','Visibilitas',['INTERNAL','WALI','UMUM'],true),f('isi_catatan','Isi Catatan','textarea',true,'span-2'),f('tindak_lanjut','Tindak Lanjut','textarea',false,'span-2'),f('tanggal_tindak_lanjut','Tanggal Tindak Lanjut','date')],async d=>panggilServer('simpanCatatan',STATE.token,d),muatCatatan);}

async function initLaporan(){await Promise.all([pastikanSantri(),pastikanKelas()]);document.getElementById('laporan-santri').innerHTML=opsiSelect(STATE.master.santri,'id_santri',x=>`${x.nomor_induk} · ${x.nama_lengkap}`,'Pilih santri');document.getElementById('laporan-kelas').innerHTML=opsiSelect(STATE.master.kelas,'id_kelas','nama_kelas','Pilih kelas');document.getElementById('laporan-awal').value=awalBulan();document.getElementById('laporan-akhir').value=hariIni();}
function ubahJenisLaporan(){const j=document.getElementById('laporan-jenis').value;document.getElementById('wrap-laporan-santri').classList.toggle('tersembunyi',j!=='SANTRI');document.getElementById('wrap-laporan-kelas').classList.toggle('tersembunyi',j==='SANTRI'||j==='KEHADIRAN'||j==='SETORAN');}
function filterLaporan(){return{awal:document.getElementById('laporan-awal').value,akhir:document.getElementById('laporan-akhir').value,id_santri:document.getElementById('laporan-santri').value,id_kelas:document.getElementById('laporan-kelas').value};}
async function pratinjauLaporan(){const j=document.getElementById('laporan-jenis').value,f=filterLaporan();tampilkanLoading('Menyusun laporan…');try{let r;if(j==='SANTRI')r=await panggilServer('laporanSantri',STATE.token,f.id_santri,{awal:f.awal,akhir:f.akhir});else if(j==='KELAS')r=await panggilServer('laporanKelas',STATE.token,f.id_kelas,{awal:f.awal,akhir:f.akhir});else if(j==='KEHADIRAN')r=await panggilServer('laporanKehadiran',STATE.token,f);else r=await panggilServer('laporanSetoran',STATE.token,f);if(!r.sukses)throw new Error(r.pesan);document.getElementById('preview-laporan').innerHTML=renderLaporan(j,r.data);}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}
function renderLaporan(j,d){if(j==='SANTRI')return `<div class="report-sheet"><h2>${escapeHtml(d.lembaga.nama)}</h2><h3>Laporan Perkembangan Santri</h3><p><strong>${escapeHtml(d.santri.nama_lengkap)}</strong> · ${escapeHtml(d.santri.nomor_induk)}<br>Periode ${formatTanggal(d.periode.awal)} s.d. ${formatTanggal(d.periode.akhir)}</p><div class="report-summary"><div><small>Kehadiran</small><strong>${d.ringkasan_kehadiran.persentase}%</strong></div><div><small>Jumlah Setoran</small><strong>${d.setoran.length}</strong></div><div><small>Nilai Akhir</small><strong>${d.nilai_rata_rata.akhir}</strong></div><div><small>Rekomendasi</small><strong>${escapeHtml(d.rekomendasi)}</strong></div></div>${tabel([{label:'Tanggal',render:x=>formatTanggal(x.tanggal)},{label:'Jenis',key:'jenis_setoran'},{label:'Nilai',key:'nilai_akhir'},{label:'Rekomendasi',render:x=>badge(x.rekomendasi)}],d.setoran)}</div>`;if(j==='KELAS')return `<div class="report-sheet"><h2>${escapeHtml(d.lembaga)}</h2><h3>Laporan Kelas ${escapeHtml(d.kelas.nama_kelas)}</h3>${tabel([{label:'Nomor Induk',key:'nomor_induk'},{label:'Nama',key:'nama_lengkap'},{label:'Kehadiran',render:x=>x.persentase_kehadiran+'%'},{label:'Setoran',key:'jumlah_setoran'},{label:'Nilai',key:'nilai_rata_rata'},{label:'Status',render:x=>badge(x.status_perkembangan)}],d.item)}</div>`;const item=d.item||[];return `<div class="report-sheet"><h3>${j==='KEHADIRAN'?'Rekap Kehadiran':'Rekap Setoran'}</h3>${j==='KEHADIRAN'?tabel([{label:'Tanggal',render:x=>formatTanggal(x.tanggal)},{label:'ID Santri',key:'id_santri'},{label:'Status',render:x=>badge(x.status_kehadiran)},{label:'Catatan',key:'catatan'}],item):tabel([{label:'Tanggal',render:x=>formatTanggal(x.tanggal)},{label:'Santri',key:'nama_santri'},{label:'Jenis',key:'jenis_setoran'},{label:'Nilai',key:'nilai_akhir'},{label:'Rekomendasi',render:x=>badge(x.rekomendasi)}],item)}</div>`;}
async function buatPdfLaporan(){const j=document.getElementById('laporan-jenis').value,f=filterLaporan();if(!['SANTRI','KELAS'].includes(j)){tampilkanToast('PDF tersedia untuk laporan santri dan kelas.','gagal');return;}tampilkanLoading('Membuat PDF di Google Drive…');try{const r=j==='SANTRI'?await panggilServer('buatPdfLaporanSantri',STATE.token,f.id_santri,{awal:f.awal,akhir:f.akhir}):await panggilServer('buatPdfLaporanKelas',STATE.token,f.id_kelas,{awal:f.awal,akhir:f.akhir});if(!r.sukses)throw new Error(r.pesan);tampilkanToast(r.pesan);window.open(r.data.url,'_blank');}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}
async function eksporLaporanCsv(){const j=document.getElementById('laporan-jenis').value,f=filterLaporan();const jenis=j==='KELAS'?'SANTRI':j;tampilkanLoading('Membuat CSV…');try{const r=await panggilServer('eksporCsv',STATE.token,jenis,f);if(!r.sukses)throw new Error(r.pesan);tampilkanToast(r.pesan);window.open(r.data.url,'_blank');}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}

async function muatPengumuman(){const r=await panggilServer('daftarPengumuman',STATE.token,{},1,100);if(!r.sukses)throw new Error(r.pesan);document.getElementById('grid-pengumuman').innerHTML=r.data.item.length?r.data.item.map(x=>`<div class="item-card"><div class="card-header"><div><h3>${escapeHtml(x.judul)}</h3><p>${formatTanggal(x.tanggal_mulai)} – ${formatTanggal(x.tanggal_selesai)}</p></div>${badge(x.prioritas)}</div><p>${escapeHtml(x.isi)}</p><div class="meta">${badge(x.sasaran)} ${badge(x.status_tayang)}</div></div>`).join(''):'<div class="empty-state">Belum ada pengumuman.</div>';}
function formTambahPengumuman(){bukaForm('Tambah Pengumuman','Informasi untuk pengguna aplikasi',[f('judul','Judul','text',true),selectF('sasaran','Sasaran',['SEMUA','PENGAJAR','WALI','KELAS'],true),selectF('prioritas','Prioritas',['NORMAL','PENTING','MENDESAK'],true),f('tanggal_mulai','Tanggal Mulai','date',true,hariIni()),f('tanggal_selesai','Tanggal Selesai','date'),f('isi','Isi Pengumuman','textarea',true,'span-2')],async d=>panggilServer('simpanPengumuman',STATE.token,d),muatPengumuman);}

function debounceMuatPengguna(){debounce('pengguna',muatPengguna)}
async function muatPengguna(){const r=await panggilServer('daftarPengguna',STATE.token,{cari:document.getElementById('cari-pengguna')?.value||''},1,100);if(!r.sukses)throw new Error(r.pesan);document.getElementById('tabel-pengguna').innerHTML=tabel([{label:'Username',key:'nama_pengguna'},{label:'Nama',key:'nama_lengkap'},{label:'Peran',render:x=>badge(x.peran)},{label:'Status',render:x=>badge(x.status_akun)},{label:'Login Terakhir',render:x=>formatTanggalWaktu(x.login_terakhir)}],r.data.item,x=>`<button class="btn kecil sekunder" onclick="resetPasswordUI('${x.id_pengguna}')">Reset Password</button>`);}
async function formTambahPengguna(){await pastikanPengajar().catch(()=>{});bukaForm('Tambah Pengguna','Akun dan hak akses',[f('nama_pengguna','Nama Pengguna','text',true),f('nama_lengkap','Nama Lengkap','text',true),f('email','Email','email'),f('nomor_whatsapp','Nomor WhatsApp','tel'),selectF('peran','Peran',['SUPER_ADMIN','PENGELOLA','ADMIN','PENGAJAR'],true),selectObjF('id_referensi','Referensi Pengajar',STATE.master.pengajar,'id_pengajar','nama_lengkap'),f('password','Password Awal','password',true)],async d=>panggilServer('simpanPengguna',STATE.token,d),muatPengguna);}
async function resetPasswordUI(id){if(!confirm('Reset password pengguna ini?'))return;tampilkanLoading('Mereset password…');try{const r=await panggilServer('resetPasswordPengguna',STATE.token,id);if(!r.sukses)throw new Error(r.pesan);bukaModalKonten('Password Sementara','Pengguna wajib mengganti password setelah login',`<div class="span-2"><label>Password<input value="${escapeHtml(r.data.password_sementara)}" readonly onclick="this.select()"></label></div>`);}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}

async function muatPengaturan(){const r=await panggilServer('ambilPengaturan',STATE.token);if(!r.sukses)throw new Error(r.pesan);const wrap=document.getElementById('form-pengaturan');wrap.innerHTML=Object.entries(r.data).map(([kelompok,items])=>`<div class="settings-group"><h4>${escapeHtml(kelompok)}</h4><div class="settings-grid">${items.map(x=>`<label>${escapeHtml(x.keterangan||x.kunci)}<input data-setting="${escapeHtml(x.kunci)}" value="${escapeHtml(x.nilai)}" ${String(x.dapat_diubah)==='TIDAK'?'disabled':''}><small>${escapeHtml(x.kunci)}</small></label>`).join('')}</div></div>`).join('');}
async function simpanSemuaPengaturan(){const data=[...document.querySelectorAll('[data-setting]:not(:disabled)')].map(x=>({kunci:x.dataset.setting,nilai:x.value}));tampilkanLoading('Menyimpan pengaturan…');try{const r=await panggilServer('simpanPengaturan',STATE.token,data);if(!r.sukses)throw new Error(r.pesan);tampilkanToast(r.pesan);await muatKonfigurasiPublik();}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}
function formGantiPassword(){bukaForm('Ganti Password','Gunakan minimal 8 karakter, huruf dan angka',[f('password_lama','Password Lama','password',true),f('password_baru','Password Baru','password',true)],async d=>panggilServer('gantiPassword',STATE.token,d.password_lama,d.password_baru));}

async function muatAudit(){const r=await panggilServer('daftarAudit',STATE.token,{modul:document.getElementById('filter-audit-modul')?.value||''},1,100);if(!r.sukses)throw new Error(r.pesan);document.getElementById('tabel-audit').innerHTML=tabel([{label:'Waktu',render:x=>formatTanggalWaktu(x.waktu)},{label:'Pengguna',key:'nama_pengguna'},{label:'Peran',render:x=>badge(x.peran)},{label:'Modul',key:'modul'},{label:'Aksi',render:x=>badge(x.aksi)},{label:'Status',render:x=>badge(x.status)},{label:'Pesan',key:'pesan'}],r.data.item);}
async function muatBackup(){const r=await panggilServer('daftarBackup',STATE.token);if(!r.sukses)throw new Error(r.pesan);document.getElementById('tabel-backup').innerHTML=tabel([{label:'Waktu',render:x=>formatTanggalWaktu(x.waktu)},{label:'Jenis',key:'jenis_backup'},{label:'Nama File',key:'nama_file'},{label:'Ukuran',render:x=>`${Math.round(Number(x.ukuran||0)/1024)} KB`},{label:'Status',render:x=>badge(x.status)}],r.data);}
async function buatBackupSekarang(){tampilkanLoading('Membuat salinan Spreadsheet…');try{const r=await panggilServer('buatBackupManual',STATE.token);if(!r.sukses)throw new Error(r.pesan);tampilkanToast(r.pesan);await muatBackup();}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}
async function pasangBackupHarian(){tampilkanLoading('Memasang trigger…');try{const r=await panggilServer('pasangTriggerBackup',STATE.token,'HARIAN');if(!r.sukses)throw new Error(r.pesan);tampilkanToast(r.pesan);}catch(e){tampilkanToast(e.message,'gagal');}finally{sembunyikanLoading();}}

async function bukaPortalWali(){document.getElementById('halaman-login').classList.add('tersembunyi');document.getElementById('shell-aplikasi').classList.add('tersembunyi');document.getElementById('halaman-portal-wali').classList.remove('tersembunyi');tampilkanLoading('Memuat portal wali…');try{const r=await panggilServer('ambilDashboardWali',TOKEN_WALI_AWAL);if(!r.sukses)throw new Error(r.pesan);const d=r.data;document.getElementById('portal-nama-lembaga').textContent=d.lembaga.nama||'Monitoring Mengaji';document.getElementById('portal-sambutan').innerHTML=`<h2>Assalamu'alaikum, ${escapeHtml(d.wali.nama_lengkap)}</h2><p>Berikut ringkasan perkembangan santri yang terhubung dengan akun wali Anda.</p>`;document.getElementById('portal-daftar-santri').innerHTML=d.santri.map(x=>`<article class="portal-santri-card"><div class="card-header"><div><h3>${escapeHtml(x.profil.nama_lengkap)}</h3><p>${escapeHtml(x.profil.nomor_induk)} · ${escapeHtml(x.profil.tingkat_aktif||'-')}</p></div>${badge(x.profil.status_santri)}</div><div class="stat-grid"><div class="stat-card"><div><small>Kehadiran Bulan Ini</small><strong>${x.persentase_kehadiran}%</strong></div></div><div class="stat-card"><div><small>Nilai Rata-rata</small><strong>${x.nilai_rata_rata}</strong></div></div><div class="stat-card"><div><small>Setoran Terbaru</small><strong>${x.setoran_terbaru.length}</strong></div></div><div class="stat-card"><div><small>Target Aktif</small><strong>${x.target_aktif.length}</strong></div></div></div><h4>Perkembangan Terbaru</h4>${x.setoran_terbaru.map(s=>`<div class="list-item"><div><strong>${formatTanggal(s.tanggal)} · ${escapeHtml(s.jenis_setoran)}</strong><small>Nilai ${s.nilai_akhir} · ${escapeHtml(s.catatan||'')}</small></div>${badge(s.rekomendasi)}</div>`).join('')||'<div class="empty-state">Belum ada setoran pada bulan ini.</div>'}<h4>Catatan Pengajar</h4>${x.catatan.map(c=>`<div class="list-item"><div><strong>${escapeHtml(c.judul)}</strong><small>${formatTanggal(c.tanggal)} · ${escapeHtml(c.isi_catatan)}</small></div>${badge(c.kategori)}</div>`).join('')||'<div class="empty-state">Belum ada catatan untuk wali.</div>'}</article>`).join('');}catch(e){document.getElementById('portal-daftar-santri').innerHTML=`<div class="empty-state"><h3>Tautan tidak dapat digunakan</h3><p>${escapeHtml(e.message)}</p></div>`;}finally{sembunyikanLoading();}}

async function pastikanKelas(){if(STATE.master.kelas.length)return STATE.master.kelas;const r=await panggilServer('ambilReferensi',STATE.token,'KELAS');if(!r.sukses)throw new Error(r.pesan);STATE.master.kelas=r.data||[];return STATE.master.kelas;}
async function pastikanSantri(){if(STATE.master.santri.length)return STATE.master.santri;const r=await panggilServer('ambilReferensi',STATE.token,'SANTRI');if(!r.sukses)throw new Error(r.pesan);STATE.master.santri=r.data||[];return STATE.master.santri;}
async function ambilSantriMasterAman(){try{return await pastikanSantri();}catch(e){return[];}}
async function pastikanPengajar(){if(STATE.master.pengajar.length)return STATE.master.pengajar;const r=await panggilServer('ambilReferensi',STATE.token,'PENGAJAR');if(!r.sukses)throw new Error(r.pesan);STATE.master.pengajar=r.data||[];return STATE.master.pengajar;}
async function pastikanWali(){if(STATE.master.wali.length)return STATE.master.wali;const r=await panggilServer('ambilReferensi',STATE.token,'WALI');if(!r.sukses)throw new Error(r.pesan);STATE.master.wali=r.data||[];return STATE.master.wali;}
async function pastikanMateri(){if(STATE.master.materi.length)return STATE.master.materi;const r=await panggilServer('ambilReferensi',STATE.token,'MATERI');if(!r.sukses)throw new Error(r.pesan);STATE.master.materi=r.data||[];return STATE.master.materi;}

function f(name,label,type='text',required=false,extra='',value=''){let span='',val=value;if(extra==='span-2')span=extra;else if(extra!==''&&value===''){val=extra;}return{name,label,type,required,span,value:val};}
function selectF(name,label,options,required=false){return{name,label,type:'select',options:options.map(x=>({value:x,label:x.replaceAll('_',' ')})),required};}
function selectObjF(name,label,items,valueKey,labelKey,required=false){return{name,label,type:'select',options:(items||[]).map(x=>({value:x[valueKey],label:typeof labelKey==='function'?labelKey(x):x[labelKey]})),required};}
function bukaForm(judul,subjudul,fields,onSubmit,setelah){STATE.modalSubmit={onSubmit,setelah};document.getElementById('modal-judul').textContent=judul;document.getElementById('modal-subjudul').textContent=subjudul||'';const form=document.getElementById('modal-form');form.innerHTML=fields.map(field=>renderField(field)).join('');form.onsubmit=prosesModalSubmit;document.getElementById('modal-simpan').classList.remove('tersembunyi');document.getElementById('modal-global').classList.add('aktif');document.getElementById('modal-global').setAttribute('aria-hidden','false');}
function renderField(x){const req=x.required?'required':'';const cls=x.span||'';if(x.type==='select')return `<label class="${cls}">${escapeHtml(x.label)}<select name="${escapeHtml(x.name)}" ${req}><option value="">Pilih ${escapeHtml(x.label)}</option>${(x.options||[]).map(o=>`<option value="${escapeHtml(o.value)}">${escapeHtml(o.label)}</option>`).join('')}</select></label>`;if(x.type==='textarea')return `<label class="${cls}">${escapeHtml(x.label)}<textarea name="${escapeHtml(x.name)}" rows="3" ${req}>${escapeHtml(x.value||'')}</textarea></label>`;return `<label class="${cls}">${escapeHtml(x.label)}<input name="${escapeHtml(x.name)}" type="${escapeHtml(x.type||'text')}" value="${escapeHtml(x.value??'')}" ${req}></label>`;}
function bukaModalKonten(judul,subjudul,html){STATE.modalSubmit=null;document.getElementById('modal-judul').textContent=judul;document.getElementById('modal-subjudul').textContent=subjudul||'';const form=document.getElementById('modal-form');form.innerHTML=html;form.onsubmit=e=>e.preventDefault();document.getElementById('modal-simpan').classList.add('tersembunyi');document.getElementById('modal-global').classList.add('aktif');document.getElementById('modal-global').setAttribute('aria-hidden','false');}
async function prosesModalSubmit(e){e.preventDefault();if(!STATE.modalSubmit)return;const btn=document.getElementById('modal-simpan');btn.disabled=true;btn.textContent='Menyimpan…';try{const r=await STATE.modalSubmit.onSubmit(nilaiForm(e.target));if(!r.sukses)throw new Error(r.pesan);tampilkanToast(r.pesan);const setelah=STATE.modalSubmit.setelah;tutupModal();STATE.master={kelas:[],santri:[],pengajar:[],wali:[],materi:[]};if(setelah)await setelah();}catch(err){tampilkanToast(err.message,'gagal');}finally{btn.disabled=false;btn.textContent='Simpan';}}
function tutupModal(){document.getElementById('modal-global').classList.remove('aktif');document.getElementById('modal-global').setAttribute('aria-hidden','true');STATE.modalSubmit=null;}

function perbaruiStatusJaringan(){
  const el=document.getElementById('status-jaringan');
  if(!el)return;
  if(navigator.onLine){el.textContent='Koneksi kembali tersedia';el.className='status-jaringan aktif online';setTimeout(()=>el.classList.remove('aktif'),2200);}
  else{el.textContent='Anda sedang offline';el.className='status-jaringan aktif';}
}
window.addEventListener('online',perbaruiStatusJaringan);
window.addEventListener('offline',perbaruiStatusJaringan);

if('serviceWorker' in navigator){
  window.addEventListener('load',async()=>{
    try{
      const registrasi=await navigator.serviceWorker.register('/service-worker.js',{scope:'/'});
      registrasi.addEventListener('updatefound',()=>{
        const pekerjaBaru=registrasi.installing;
        if(!pekerjaBaru)return;
        pekerjaBaru.addEventListener('statechange',()=>{
          if(pekerjaBaru.state==='installed'&&navigator.serviceWorker.controller){
            const banner=document.getElementById('update-banner');
            if(banner)banner.classList.add('aktif');
          }
        });
      });
    }catch(error){console.warn('Service worker tidak dapat dipasang:',error);}
  });
}
function terapkanPembaruan(){window.location.reload();}

